import type { Metadata } from "next";
import {JetBrains_Mono} from "next/font/google";
import "./globals.css";

const jetbrains = JetBrains_Mono({ subsets: ['latin'], weight: ['400', '500', '700'] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
      <link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/devicons/devicon@latest/devicon.min.css" />
      </head>
     <body className={`${jetbrains.className} scroll-smooth bg-gradient-to-br from-[#0a0a0a] via-[#1e0f2f] to-[#000000] text-white`}>
        {children}
      </body>
    </html>
  );
}
